### ISSUE TITLE
App password not working after expired password change

### ISSUE THREAD

**Issue by phil-davis** [owncloud/password_policy#33] opened 2018-07-10 06:24 UTC
Steps to reproduce:
1. Have ``password_policy`` enabled.
2. Create a user ``testuser``.
3. Login as ``testuser``, create an app password and keep a copy of it.
4. Logout and login again as ``testuser`` using the app password - it works, good.
5. Logout and login again as ``testuser`` using the ordinary password.
6. Change your password.
7. Logout and login again as ``testuser`` using the app password - it still works, good.
8. Logout and login again as ``testuser`` using the changed password.
9. Logout
10. Wait until the password expires, or expire it:
```
./occ user:expire-password <username>
```
11. Login again as ``testuser`` using the changed password.
12. You are taken to the password change page - change your password.
13. Logout and login again as ``testuser`` using the app password

"Internal Server Error" is displayed in the browser.
Server has:
```
[Tue Jul 10 12:08:06 2018] Login failed: 'test8888' (Remote IP: '192.168.0.103')
[Tue Jul 10 12:08:06 2018] Exception: {"Exception":"Error","Message":"Call to a member function getUID() on null","Code":0,"Trace":"#0 \/home\/phil\/git\/owncloud\/core\/lib\/private\/User\/Session.php(883): OC\\User\\Session->checkTokenCredentials(Object(OC\\Authentication\\Token\\DefaultToken), 'CQWDD-VBCAT-LOZ...')\n#1 \/home\/phil\/git\/owncloud\/core\/lib\/private\/User\/Session.php(331): OC\\User\\Session->validateToken(*** sensitive parameters replaced ***)\n#2 \/home\/phil\/git\/owncloud\/core\/core\/Controller\/LoginController.php(204): OC\\User\\Session->login(*** sensitive parameters replaced ***)\n#3 [internal function]: OC\\Core\\Controller\\LoginController->tryLogin(*** sensitive parameters replaced ***)\n#4 \/home\/phil\/git\/owncloud\/core\/lib\/private\/AppFramework\/Http\/Dispatcher.php(159): call_user_func_array(Array, Array)\n#5 \/home\/phil\/git\/owncloud\/core\/lib\/private\/AppFramework\/Http\/Dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OC\\Core\\Controller\\LoginController), 'tryLogin')\n#6 \/home\/phil\/git\/owncloud\/core\/lib\/private\/AppFramework\/App.php(103): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OC\\Core\\Controller\\LoginController), 'tryLogin')\n#7 \/home\/phil\/git\/owncloud\/core\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(46): OC\\AppFramework\\App::main('LoginController', 'tryLogin', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#8 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#9 \/home\/phil\/git\/owncloud\/core\/lib\/private\/Route\/Router.php(342): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#10 \/home\/phil\/git\/owncloud\/core\/lib\/base.php(919): OC\\Route\\Router->match('\/login')\n#11 \/home\/phil\/git\/owncloud\/core\/index.php(55): OC::handleRequest()\n#12 {main}","File":"\/home\/phil\/git\/owncloud\/core\/lib\/private\/User\/Session.php","Line":825}
[Tue Jul 10 12:08:06 2018] 192.168.0.103:46502 [500]: /index.php/login
```
and similar problems if you try to use the app password in ``curl`` commands etc.

**Comment by phil-davis** [comment] 2018-07-10 06:30
Normally an app password works fine to login to the webUI, as well as to use as a password in a client app that is accessing the server via the various APIs. So I used app passwords logging in to the webUI in the steps here just to demonstrate the problem. It is a similar issue if you have a client app.

The user can change their password voluntarily in the Settings->General webUI page, and their app passwords keep working.

But if they are forced to change their password through the password-expiry password change page, then something different seems to be happening that breaks their app passwords.

**Comment by phil-davis** [comment] 2018-07-10 06:45
@davitol can you (or anyone else) reproduce this?

I have made it happen a couple of times. But I am still a bit suspicious that the 5-minute checks for tokens/passwords might mean that the problem happens after 5 minutes, or some other timing thing, rather than always exactly as described.

**Comment by PVince81** [comment] 2018-07-10 10:16
Slightly related: https://github.com/owncloud/core/issues/26731

**Comment by PVince81** [comment] 2018-07-12 14:39
@phil-davis is there a workaround or a way to recover from this ?

**Comment by phil-davis** [comment] 2018-07-12 14:44
I have not found a work-around. But I have not come back to this again. I will reproduce again in the morning, just to be confident in the sequence of events - because it seems a really weird thing that the user changing the password "voluntarily" in the webUI vs being forced to change it, results in different side-effects.

**Comment by PVince81** [comment] 2018-07-12 14:51
now thinking of it, a user is not supposed to use web UI with app password so might be fine...

would be good to find out how desktop client behaves with app password after expiry.

Based on https://github.com/owncloud/core/issues/26731 I'd expect the desktop client to ask for a new password as the old app password would be expired as well.

**Comment by PVince81** [comment] 2018-07-12 16:21
While trying to reproduce, found this issue just before that:

"App password continue working while main password is marked as expired"

1. Enable password expiry rules with defaults
1. Create a user "user1"
1. Login as "user1"
1. Create app password
1. Log out
1. `curl -D - -X PROPFIND -u user1:QNAXS-BRBLP-HVJSA-QESCB http://localhost/owncloud/remote.php/dav/files/user1/` => correct DAV response
1. occ user:expire-password user1 -- "-4 days"
1. same curl again => DAV response, still
1. open web UI for user1
1. enter regular main password
1. see expiry page
1. curl again => DAV response, still

@butonic @pmaier1 I'd say that this behavior I see is by design. The reason for asking for a password change is usually due to password weakness. So while the main password stops working it is ok for app passwords to continue working.

**Comment by PVince81** [comment] 2018-07-12 16:24
and just after the steps from https://github.com/owncloud/password_policy/issues/33#issuecomment-404569575, the next step:

13. in the expiry page, change the user password
14. curl again => :boom: 

The logging statements in core fail because '$this->activeUser` is not defined here: https://github.com/owncloud/core/blob/stable10/lib/private/User/Session.php#L821

It's a bit sad that a log statement can break stuff like this. I'll add an extra check for safety... Needs little core change. Ideal would be to change the original condition there.

**Comment by PVince81** [comment] 2018-07-12 17:03
Core bug: https://github.com/owncloud/core/issues/32038

Reproducible also with resetting password.

The key is to comment out the "lastCheck" in the token code. See above ticket first step.

**Closed by PVince81** 2018-07-12 17:03 UTC
Labels: bug-analysis
