### ISSUE TITLE
Notify when user password is about to expire or expired

### ISSUE THREAD

**Issue by PVince81** [owncloud/password_policy#18] opened 2018-07-04 12:53 UTC
### High level
- [x] User should be notified X days before the password expires to change the password (when remaining days is exactly X days): the notification mentions how many days (X). X defaults to 30 days
- [ ] ~~User should be notified every day before expiration after Y or less days are left (notifications can pile up), the notification mentions how many days left (it will count down every day). Y defaults to 7 days~~
- [x] User should be notified when the password has expired

### Tech detail
- [x] We need a cron job that reads the expiration values (wherever they are stored now) and sends a single notification.
- [x] Might need to write down a flag in the user preferences to track that a notification was already sent.
- [x] When changing the password, the flag must be reset to make sure notifications will be sent again.
- [x] Notification URL points to settings page to change user password
- [x] Notification must have an action set so that it also gets sent by email.
    - [ ] Action URL should point to the settings page for changing the password, if redirecting is possible.
    - [ ] Else: Have JS code in password policy app intercept the event for the button click and redirect to the settings page for changing password
- [ ] Skip any user from a backend that doesn't support the "set password" capability (expiration not support with LDAP for example)
- [ ] Trigger Symfony event for both events ?

**Comment by phil-davis** [comment] 2018-07-04 13:35
What does it mean in practice, that the user should be notified when the password has expired?
If it is an "internal" notification that comes, for example, on the webUI, then they will never see it. Because when they try to login, they will either be taken directly to a password change screen and have to change their password to login, or their account will have got locked out (if that is a possibility for users that wait ages after their password has expired)

**Comment by PVince81** [comment] 2018-07-04 13:38
We might need to add an action URL to the notification to make sure the notification system also sends it by email. The default option only sends by mail when an action is required). The URL should point at the page for changing the password if possible.

Now I'm not sure whether password expiry automatically kicks the users out of the system. If not, they might still see the notification.

**Comment by jvillafanez** [comment] 2018-07-04 14:01
> User should be notified Y days before the password expires to change the password

Is this hardcoded or configurable? I guess hardcoded for now, but configurable in the (near) future

> We need a cron job that reads the expiration values (wherever they are stored now) and sends a single notification.

Do we want a heavy long running job that runs once per day, or multiple smaller jobs that runs maybe once per hour?

> Notification must have an action URL so that it also gets sent by email. Action URL should point to the page for changing the password, if possible.

I guess we'll need to use a "go there" button or similar. However I'm not sure if that's going to work because the actions are supposed to be executed via ajax. This doesn't look good at first sight.

**Comment by PVince81** [comment] 2018-07-04 14:35
> Is this hardcoded or configurable? I guess hardcoded for now, but configurable in the (near) future

Let's make that an oc_appconfig setting with a default value until we clarify whether and when to build the UI. If adding a number field in the UI is trivial, just do it right away.

**Comment by PVince81** [comment] 2018-07-04 14:39
> Do we want a heavy long running job that runs once per day, or multiple smaller jobs that runs maybe once per hour?

Depending on the implementation. If we can select all values in a single query from oc_preferences, we could then find the list of user ids to notify. I haven't looked at the current code but would expect that the timestamp from the last password change should be in the DB.

In this case the "heavy" job shouldn't be that heavy as we wouldn't iterate over all users, I guess that's what you had in mind.

> I guess we'll need to use a "go there" button or similar. However I'm not sure if that's going to work because the actions are supposed to be executed via ajax. This doesn't look good at first sight.

Yes, this worries me as well. Currently the notifications app is not designed to understand or respond to a redirect. We might need to extend the notifications app to also have an action field telling it to redirect to some URL.

The alternative is no action URL at all. This also means these notifications will never be sent by email unless the admin has chosen the non-default setting to always send all notifications by email.

**Comment by PVince81** [comment] 2018-07-04 14:40
@jvillafanez I've updated the first post with some discussed details

**Comment by PVince81** [comment] 2018-07-04 15:53
I've updated the post again to say that we do want a notification action. The button can likely be intercepted by JS code provided by the password policy app. Needs to research whether that is possible.

**Comment by jvillafanez** [comment] 2018-07-04 16:33
> look into doing a SELECT on the oc_preferences table to find the user_ids to notify

It doesn't seem possible.

Assuming that the column contains a numeric value (something we shouldn't do because the column contains text):
* mysql seems to work fine.
* postgresql requires casting to an integer (?) type. This datatype casting might be dependent on the DBMS, so we can't assume that using "integer" will work everywhere.
* oracle can't cast explicitly nor implicitly to a integer value if the column is CLOB

Taking into account the risks and that will likely have to do testing on each DB for any solution, I'd recommend another approach. We also need to consider that the password_policy app shouldn't access to the preferences table directly.

We might still need to traverse all the users. Using `getUserValueForUsers` should help to hit less times the DB server, unless we want to add something specific (we might also check indexes in this case)

**Comment by karakayasemi** [comment] 2018-07-04 17:04
> I haven't looked at the current code but would expect that the timestamp from the last password change should be in the DB.

@PVince81 we are storing all password changes in this apps password history table. Maybe it can help.
https://github.com/owncloud/password_policy/blob/master/appinfo/Migrations/Version20180123143343.php#L50

**Comment by butonic** [comment] 2018-07-04 21:17
@karakayasemi @PVince81 correct.
- [ ] a daily background job needs to check the latest password of all users using the password history table of this app. no need to store anything in the oc_preferences table. The notification interfaces
```
use OCP\Notification\IManager;
use OCP\Notification\INotification;
use OCP\Notification\INotifier;
```
should work, looking at the `updatenotification` app.

- the password policy app should get a new config option to configure
  - [ ] the number of days when the user gets notified that his password is going to expire, default to 14 days
  - [ ] the number of days the user gets notified every day before the password expires, default to 7
  - reuse this apps Engine and the config ui that exists to keep it consistent.

**Comment by PVince81** [comment] 2018-07-05 08:06
@butonic is "change_time" also adjusted when the password was changed in LDAP ? If not we might be expiring passwords at the wrong time. Unless we say expiration is not supposed when using LDAP and need to be handled on LDAP level instead ?

**Comment by butonic** [comment] 2018-07-05 08:16
LDAP / AD have their own password expiry mechanism. Only supposed to work for database users

**Comment by PVince81** [comment] 2018-07-05 09:29
> LDAP / AD have their own password expiry mechanism. Only supposed to work for database users

Hmmm, this tells me we should then still be careful and make sure the expiration logic and also the notification logic skips non-DB users.

**Comment by PVince81** [comment] 2018-07-05 09:29
... or broader, skip any user from a backend that doesn't support the "set password" capability

**Comment by phil-davis** [comment] 2018-07-05 09:33
Good thoughts - I better try some password_policy with LDAP scenarios and make sure LDAP users do not get locked out.

**Comment by PVince81** [comment] 2018-07-05 10:04
I've added " Skip any user from a backend that doesn't support the "set password" capability (expiration not support with LDAP for example)" as checkbox

**Comment by PVince81** [comment] 2018-07-05 16:04
I've added another checkbox as we also need a daily reminder when days until expiration are 7 or less.

**Comment by jvillafanez** [comment] 2018-07-06 10:18
For the sake of easier testing, I'll store the timings in seconds instead of days. The expectation is that the UI (when ready) ask for days but store the information as seconds.
We should consider to do the same for the expiration time, but that's something out of the scope at the moment.

**Comment by phil-davis** [comment] 2018-07-06 10:59
@jvillafanez in the current (unreleased yet, I think) code, there is ``90`` "days until user password expires.
I guess you are going to retrofit that now so that the expiry will be stored in seconds?
(as well as the new settings)

That will also be nice for testing.

And even nicer if there is a way to specify seconds, instead of days, in a command somewhere that sets these values.

**Comment by jvillafanez** [comment] 2018-07-06 11:38
> I guess you are going to retrofit that now so that the expiry will be stored in seconds?
(as well as the new settings)

Not for now because there are several changes involved and also we'll need to write a migration. We're already in a tight schedule to add more things.

**Comment by PVince81** [comment] 2018-07-06 12:38
@phil-davis separate ticket maybe ?

**Comment by PVince81** [comment] 2018-07-06 12:44
Removed "daily notification" in original post after talking with @pmaier1 about requirements. It was a misunderstanding.

**Comment by phil-davis** [comment] 2018-07-06 13:10
> separate ticket maybe ?
If the new version of the app gets released with the new "days until user password expires" setting and it is in the database in days, then there will be a migration-conversion needed when the later version is released to store it in seconds. So it would be much easier to make this change before release.

I guess I can make a separate ticket to change just that.

**Comment by jvillafanez** [comment] 2018-07-09 10:55
@pmaier1 I'll need some texts for the notifications:

current text for the reminder
![screen shot 2018-07-09 at 12 44 54](https://user-images.githubusercontent.com/1477829/42446384-52a9566a-8376-11e8-8437-7b917f6876c9.png)

current text for the "password expired"
![screen shot 2018-07-09 at 12 45 52](https://user-images.githubusercontent.com/1477829/42446391-58e3eae0-8376-11e8-9b89-36d7eb75aaf9.png)

![screen shot 2018-07-09 at 12 47 42](https://user-images.githubusercontent.com/1477829/42446400-5ff96922-8376-11e8-934b-f8972d03c2b8.png)


I'll also need to know when the cron job will run. It's set to run each 12 hours for now. We might want to increase the time to 24 hours. If the interval can be configurable (I don't know) we might want to let the admin configure this option too.

**Comment by jvillafanez** [comment] 2018-07-09 11:12
> Skip any user from a backend that doesn't support the "set password" capability (expiration not support with LDAP for example)

Shouldn't this be applicable to the whole password_policy app?

I'm not sure if I should do anything in this regard in the cron job. I mean, the problem should be handled across the whole app: an LDAP user might get locked out of ownCloud regardless a notification being sent or not because we can't change the password from ownCloud.

Right now, the cron job heavily depends on the information stored in the user_password_history. If the password isn't there, the notification won't be sent.

Maybe LDAP users shouldn't have an entry in the user_password_history in the first place.

**Comment by PVince81** [comment] 2018-07-09 12:24
> Maybe LDAP users shouldn't have an entry in the user_password_history in the first place.

Good idea. I suspect that if passwords are only changed over LDAP, we cannot detect this anyway so the field will never have a value. And if it did, it would be ok because the OC notification would then ask users to rather go to LDAP to change their password.

**Comment by PVince81** [comment] 2018-07-09 12:43
@jvillafanez I retract what I said. Based on https://github.com/owncloud/password_policy/issues/24 we cannot rely on empty values to detect what users to process as we need to fall back to a default value.

**Comment by phil-davis** [comment] 2018-07-09 12:49
With the existing code, I don't think LDAP users will ever get an entry in ``user_password_history`` because neither they, not the admin, ever change an LDAP user password inside ownCloud.

To be doubly-sure, ```password_policy`` code can specifically ignore users that have LDAP or other external-auth backends. But I suspect that extra check will not be needed.

**Comment by jvillafanez** [comment] 2018-07-10 10:18
> Notification must have an action set so that it also gets sent by email.

I think we should skip this point for now and sent the notification without action. We might want to add a point in the release notes about this: you'll need to enable the sending of all notifications via email to get the email.

The problem is that there is no support for this right now, and adding the support will need more changes. We have to agree on how we can deal with this scenario, and in any case we have to make changes in the notification app.

There are several solutions:
* The action returns a redirection (HTTP code 302). This doesn't work because we can't neither handle the redirection in js (jquery redirects to the page automatically) nor ensure such redirection should be treated differently.
* The action can return an specific json object, something like `{'redirectTo': '/apps/files'}`. The problem is that this response can be a "valid" one for the endpoint. The interaction with the notifications app might not be wanted.
* The notification app can trigger an event / promise when the app is loaded in js. This could allow other apps to include custom code to handle their own notifications when the notification app is there. Note that there will be dependencies between apps in this case, and other apps not related to the main one (usually files) might take over.

**Comment by PVince81** [comment] 2018-07-10 11:46
I was currently hoping we could go with the JS approach in the third bullet point. Isn't there already a jQuery event triggered by the notification that we could listen to ?

**Comment by jvillafanez** [comment] 2018-07-10 12:31
Yes, but it's more tricky than what we did for files_sharing:

What we did for files_sharing assumed that the response for the action happened in the files app. The files_sharing code we need to include is always loaded within the files app (it makes sense as files_sharing has to deal with files), but it isn't loaded outside (or at least it shouldn't). The files_sharing's js code doesn't care if the action is triggered outside of the files app.

This new case is different: no matter where we are, we have to redirect the user to the password_policy app once the action is executed. This means that we have to include js code from the password_policy app somehow wherever the notifications app is present. Basically, all apps should include js code from the password_policy app.
There is the additional problem of who is responsible of redirecting the user: is it the password_policy app (which as said, needs its code to be injected somehow)? is it the notification app (more or less aligned with the first or second bullet points)?, is it each app containing the bell icon?

**Comment by PVince81** [comment] 2018-07-10 15:29
You can load app JS code in app.php and it will be present regardless of what app is currently presented. Many other apps already do that, not a big issue.
The only risk I see is if there are old password policy notifications while the app has been disabled.

For now I'd say password policy JS handler would take care of the redirect. It's not a clean solution but would allow us to avoid touching 10.0.9 now for the current password policy release. In 10.0.10 we can look into making the redirect more official by having such actions implemented. Raised here https://github.com/owncloud/notifications/issues/212

**Comment by PVince81** [comment] 2018-07-10 15:30
> is it each app containing the bell icon?

The bell icon is part of the notification app itself. The notification app loads itself on every page through app.php and embed the bell into the header.

**Comment by PVince81** [comment] 2018-07-10 15:31
ref https://github.com/owncloud/notifications/blob/master/appinfo/app.php#L34

it does check whether the user is logged in though

**Comment by PVince81** [comment] 2018-07-10 20:18
@jvillafanez here we go, works with JS with an interesting trick: https://github.com/owncloud/password_policy/pull/27#issuecomment-403951044

Also note that if we removed the "parsed action" the email is still sent but no button is displayed.

I'll chat with @pmaier1 tomorrow, maybe seeing the button is still better as it incites to action

**Comment by PVince81** [comment] 2018-07-10 20:20
PR is here: https://github.com/owncloud/password_policy/pull/27

**Comment by jvillafanez** [comment] 2018-07-11 08:39
For a quick fix, I guess will have to go with that solution, at least for the moment. 🙈 

> Also note that if we removed the "parsed action" the email is still sent but no button is displayed.

You're still supposed to parse the action. If you don't do it I'd expect explosions at some point. Using this to "hide" the button is bad.

**Closed** 2018-07-12 14:18 UTC
Labels: enhancement, p2-high
